"""add tests

Revision ID: d8745058c655
Revises: 
Create Date: 2018-02-28 23:11:59.825086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8745058c655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_name'), 'test', ['name'], unique=True)
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_result_name'), 'test_result', ['name'], unique=True)
    op.create_table('test_suite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suite_name'), 'test_suite', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_suite_name'), table_name='test_suite')
    op.drop_table('test_suite')
    op.drop_index(op.f('ix_test_result_name'), table_name='test_result')
    op.drop_table('test_result')
    op.drop_index(op.f('ix_test_name'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
